name: test
run-name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Make it able to be used in other workflows
  workflow_call:

jobs:
  pre-commit:
    name: Check pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  build_and_test:
    name: Check pre-commit
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v2.4.0
    needs: [ pre-commit ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "🔎 Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Clone nlohmann json
        uses: actions/checkout@master
        with:
          repository: nlohmann/json
          path: nlohmann-json
          ref: v3.11.2
      - name: Build and install nlohmann json
        run: |
          cd nlohmann-json
          cmake -S . -B build
          cmake --build build --target install -j$(nproc)
          cd ..
      - name: Clone json-schema-validator
        uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build
      - name: build
        run: cmake --build build --target all -j$(nproc)
      - name: test
        run: cd build && ctest
  build_and_test_min_version:
    name: Check pre-commit
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v2.4.0
    needs: [ pre-commit ]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "🔎 Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Clone nlohmann json
        uses: actions/checkout@master
        with:
          repository: nlohmann/json
          path: nlohmann-json
          ref: v3.8.0
      - name: Build and install nlohmann json
        run: |
          cd nlohmann-json
          cmake -S . -B build
          cmake --build build --target install -j$(nproc)
          cd ..
      - name: Clone json-schema-validator
        uses: actions/checkout@v3
      - name: cmake
        run: cmake -S . -B build
      - name: build
        run: cmake --build build --target all -j$(nproc)
      - name: test
        run: cd build && ctest
